INFO: To setup environment run:
      eval "$(/apps/languages/anaconda/2024.02/bin/conda shell.bash hook)"
  or just:
      source activate
Traceback (most recent call last):
  File "/home/c.c22091860/.conda/envs/marble/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/c.c22091860/.conda/envs/marble/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/scratch/c.c22091860/MARBLE-Benchmark/./__main__.py", line 89, in <module>
    args.main_func(args)
  File "/scratch/c.c22091860/MARBLE-Benchmark/./benchmark/extract.py", line 27, in main
    extract_main(config)
  File "/scratch/c.c22091860/MARBLE-Benchmark/./benchmark/models/mule/extract_mule_features.py", line 44, in main
    download_model()
  File "/scratch/c.c22091860/MARBLE-Benchmark/./benchmark/models/mule/extract_mule_features.py", line 28, in download_model
    wget.download(link, out=download_dir)
  File "/home/c.c22091860/.conda/envs/marble/lib/python3.9/site-packages/wget.py", line 526, in download
    (tmpfile, headers) = ulib.urlretrieve(binurl, tmpfile, callback)
  File "/home/c.c22091860/.conda/envs/marble/lib/python3.9/urllib/request.py", line 239, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
  File "/home/c.c22091860/.conda/envs/marble/lib/python3.9/urllib/request.py", line 214, in urlopen
    return opener.open(url, data, timeout)
  File "/home/c.c22091860/.conda/envs/marble/lib/python3.9/urllib/request.py", line 523, in open
    response = meth(req, response)
  File "/home/c.c22091860/.conda/envs/marble/lib/python3.9/urllib/request.py", line 632, in http_response
    response = self.parent.error(
  File "/home/c.c22091860/.conda/envs/marble/lib/python3.9/urllib/request.py", line 561, in error
    return self._call_chain(*args)
  File "/home/c.c22091860/.conda/envs/marble/lib/python3.9/urllib/request.py", line 494, in _call_chain
    result = func(*args)
  File "/home/c.c22091860/.conda/envs/marble/lib/python3.9/urllib/request.py", line 641, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found
